package com.lonestarcell.mtn.design.agent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PanelUIDesign extends VerticalLayout {
	protected VerticalLayout cHeader;
	protected VerticalLayout userIdentity;
	protected HorizontalLayout usernameMore;
	protected Label username;
	protected Button userOps;
	protected VerticalLayout moreDropDown;
	protected VerticalLayout logoArea;
	protected VerticalLayout midContent;
	protected Panel leftBar;
	protected VerticalLayout rightContent;
	protected Panel content;
	protected VerticalLayout cAds;
	protected VerticalLayout cMobileAd;
	protected HorizontalLayout cMM2;
	protected VerticalLayout cMMSlogan2;
	protected VerticalLayout cCardAd;
	protected HorizontalLayout cMM3;
	protected VerticalLayout cMMSlogan3;
	protected VerticalLayout cLastCard;
	protected HorizontalLayout cMM5;
	protected VerticalLayout cMMSlogan5;
	protected VerticalLayout cMobileAd6;
	protected HorizontalLayout cMM15;
	protected VerticalLayout cMMSlogan15;
	protected VerticalLayout cCardAd5;
	protected HorizontalLayout cMM16;
	protected VerticalLayout cMMSlogan16;
	protected VerticalLayout cLastCard5;
	protected HorizontalLayout cMM17;
	protected VerticalLayout cMMSlogan17;
	protected HorizontalLayout footerMain;
	protected Label footerYearSeparator;
	protected Label footerCurretYr;
	protected Label footerPlatformBoss;

	public PanelUIDesign() {
		Design.read(this);
	}
}
