package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BackupDNewUserFormUIDesign extends VerticalLayout {
	protected VerticalLayout cHeader;
	protected VerticalLayout userIdentity;
	protected HorizontalLayout usernameMore;
	protected Label username;
	protected Button userOps;
	protected VerticalLayout moreDropDown;
	protected VerticalLayout logoArea;
	protected VerticalLayout midContent;
	protected Panel leftBar;
	protected VerticalLayout rightContent;
	protected Panel content;
	protected VerticalLayout cForms;
	protected VerticalLayout cBookingDetails3;
	protected HorizontalLayout cBDHead3;
	protected VerticalLayout cMobileNumber3;
	protected HorizontalLayout cControls3;
	protected Button btnCancel3;
	protected Button btnNext3;
	protected HorizontalLayout footerMain;
	protected Label footerYearSeparator;
	protected Label footerCurretYr;
	protected Label footerPlatformBoss;

	public BackupDNewUserFormUIDesign() {
		Design.read(this);
	}
}
