package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DDashTxnUIDesign extends VerticalLayout {
	protected VerticalLayout cMobileAd7;
	protected HorizontalLayout cMM18;
	protected Label lbCapturedBookings;
	protected Label lbInfoDesc;
	protected VerticalLayout cCardAd6;
	protected HorizontalLayout cMM19;
	protected Label lbSuccessTrxns;
	protected VerticalLayout cMMSlogan18;
	protected VerticalLayout cLastCard6;
	protected HorizontalLayout cMM20;
	protected Label lbFailedTrxns;
	protected VerticalLayout cMobileAd8;
	protected HorizontalLayout cMM21;
	protected Label lbProcessingTrxns;
	protected VerticalLayout cCardAd7;
	protected HorizontalLayout cMM22;
	protected Label lbTotalTrxns;
	protected VerticalLayout cMMSlogan19;
	protected VerticalLayout cLastCard7;
	protected HorizontalLayout cMM23;

	public DDashTxnUIDesign() {
		Design.read(this);
	}
}
