package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DDashTxnUIDesign extends VerticalLayout {
	protected VerticalLayout cMobileAd712;
	protected HorizontalLayout cMM1812;
	protected Label lbSubPer;
	protected Label lbSub;
	protected Label lbInfoDesc12;
	protected Button btnSubSuccess;
	protected Button btnSubOther;
	protected Button btnSubTotal;
	protected Button btnRefreshSub;
	protected VerticalLayout cMobileAd73;
	protected HorizontalLayout cMM183;
	protected Label lbMerPer;
	protected Label lbMer;
	protected Label lbInfoDesc3;
	protected Button btnMerSuccess;
	protected Button btnMerOther;
	protected Button btnMerTotal;
	protected Button btnRefreshMer;
	protected VerticalLayout cMobileAd711;
	protected HorizontalLayout cMM1811;
	protected Label lbTxnPer;
	protected Label lbTxn;
	protected Label lbInfoDesc11;
	protected Button btnTxnSuccess;
	protected Button btnTxnOther;
	protected Button btnTxnTotal;
	protected Button btnRefreshTxn;
	protected VerticalLayout cMobileAd7211;
	protected HorizontalLayout cMM18211;
	protected Label lbUserPer;
	protected Label lbUser;
	protected Label lbInfoDesc211;
	protected Button btnUserActive;
	protected Button btnUserOther;
	protected Button btnUserTotal;
	protected Button btnRefreshUser;

	public DDashTxnUIDesign() {
		Design.read(this);
	}
}
