package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DDashTxnUIDesign extends VerticalLayout {
	protected VerticalLayout cMobileAd71;
	protected HorizontalLayout cMM181;
	protected Label lbTxnPer;
	protected Label lbTxn;
	protected Label lbInfoDesc1;
	protected Button btnTxnSuccess;
	protected Button btnTxnFail;
	protected Button btnTxnTotal;
	protected VerticalLayout cMobileAd7;
	protected HorizontalLayout cMM18;
	protected Label lbSMSPer;
	protected Label lbSMS;
	protected Label lbInfoDesc;
	protected Button btnSMSSuccess;
	protected Button btnSMSFail;
	protected Button btnSMSTotal;
	protected VerticalLayout cMobileAd711;
	protected HorizontalLayout cMM1811;
	protected Label lbTokenPer;
	protected Label lbToken;
	protected Label lbInfoDesc11;
	protected Button btnTokenSuccess;
	protected Button btnTokenFail;
	protected Button btnTokenTotal;
	protected VerticalLayout cMobileAd72;
	protected HorizontalLayout cMM182;
	protected Label lbInfoPer;
	protected Label lbInfo;
	protected Label lbInfoDesc2;
	protected Button btnInfoSuccess;
	protected Button btnInfoFail;
	protected Button btnInfoTotal;

	public DDashTxnUIDesign() {
		Design.read(this);
	}
}
