package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DManagementUIDesign extends VerticalLayout {
	protected VerticalLayout cHeader;
	protected VerticalLayout userIdentity;
	protected HorizontalLayout usernameMore;
	protected Label lbUsername;
	protected Button btnUserOps;
	protected VerticalLayout moreDropDown;
	protected Button btnFxRate;
	protected Button btnPlaces;
	protected Button btnUserProfile;
	protected Button btnLogout;
	protected VerticalLayout logoArea;
	protected Button btnHMenuDash;
	protected Button btnHMenuTxn;
	protected Button btnHMenuPayment;
	protected Button btnHMenuToken;
	protected Button btnHMenuInfo;
	protected Button btnHMenuUser;
	protected Button btnHMenuMisc;
	protected VerticalLayout midContent;
	protected Panel leftBar;
	protected Button btnDashboard;
	protected Button btnNewUser;
	protected Button btnNewReserv;
	protected Button btnTodaysBooking;
	protected Button btnUsers;
	protected Button btnPaymentReports;
	protected Button btnBookingReports;
	protected VerticalLayout rightContent;
	protected VerticalLayout cMainContent;
	protected VerticalLayout cAds;
	protected HorizontalLayout footerMain;
	protected HorizontalLayout cOwnership;
	protected Label lbCRYearStart;
	protected Label lbYearSeparator;
	protected Label lbCRYearCurrent;
	protected Label lbClient;

	public DManagementUIDesign() {
		Design.read(this);
	}
}
