package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DReportsUIDesign extends VerticalLayout {
	protected VerticalLayout cForms;
	protected VerticalLayout cBookingDetails3;
	protected VerticalLayout headBookedScheduledFlights2;
	protected CheckBox chkDateFilter;
	protected PopupDateField dFStartDate;
	protected PopupDateField dFLastDate;
	protected Button btnFilter;
	protected Button btnReload;
	protected VerticalLayout vlTrxnTable;

	public DReportsUIDesign() {
		Design.read(this);
	}
}
