package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DRoleUIDesign extends VerticalLayout {
	protected VerticalLayout headBookedScheduledFlights2;
	protected Label lbFormHeader;
	protected VerticalLayout cMobileNumber3;
	protected Label lbNormalMsg;
	protected Label lbErrorMsg;
	protected Accordion accoRoles;
	protected HorizontalLayout cControls3;
	protected Button btnAddNewRole;

	public DRoleUIDesign() {
		Design.read(this);
	}
}
