package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DTxnDetailsUIDesign extends VerticalLayout {
	protected VerticalLayout cMMRightContent;
	protected HorizontalLayout detailsHead;
	protected Panel detailsPanel;
	protected HorizontalLayout cBDHead211;
	protected Button btnTxnDetailsClose;
	protected VerticalLayout cBookingDetails2;
	protected HorizontalLayout cBDHead3;
	protected Label lbReqSID;
	protected Label lbReqMoId;
	protected Label lbReqRateId;
	protected VerticalLayout cBookingDetails11;
	protected HorizontalLayout cBDHead11;
	protected Label lbReqMSISDN;
	protected Label lbReqAmount;
	protected VerticalLayout cBookingDetails21;
	protected HorizontalLayout cBDHead31;
	protected Label lbReqCur;
	protected Label lbReqRate;
	protected VerticalLayout cBookingDetails111;
	protected HorizontalLayout cBDHead111;
	protected Label lbReqDateC;
	protected Label lbReqDateE;
	protected Label lbReqStatus;
	protected Button btnTxnRefresh;
	protected HorizontalLayout cBDHead2;
	protected VerticalLayout cBookingDetails;
	protected HorizontalLayout cBDHead;
	protected Label lbItronSID;
	protected Label lbItronVerifId;
	protected Label lbItronTokenId;
	protected VerticalLayout cBookingDetails1;
	protected HorizontalLayout cBDHead1;
	protected Label lbItronMeterNo;
	protected Label lbItronAmount;
	protected VerticalLayout cBookingDetails3;
	protected HorizontalLayout cBDHead4;
	protected Label lbItronVerifDateC;
	protected Label lbItronVerifDateE;
	protected Label lbItronVerifStatus;
	protected VerticalLayout cBookingDetails12;
	protected HorizontalLayout cBDHead12;
	protected Label lbItronTokenDateC;
	protected Label lbItronTokenDateE;
	protected Label lbItronTokenStatus;
	protected Button btnTokenRetry;
	protected HorizontalLayout cBDHead22;
	protected VerticalLayout cBookingDetails4;
	protected HorizontalLayout cBDHead5;
	protected Label lbSmsSID;
	protected Label lbSmsID;
	protected VerticalLayout cBookingDetails13;
	protected HorizontalLayout cBDHead13;
	protected Label lbSmsMeterNo;
	protected Label lbSmsMSISDN;
	protected Label lbSmsAmount;
	protected VerticalLayout cBookingDetails31;
	protected HorizontalLayout cBDHead41;
	protected Label lbSmsToken;
	protected Label lbSmsUnits;
	protected VerticalLayout cBookingDetails121;
	protected HorizontalLayout cBDHead121;
	protected Label lbSmsDateC;
	protected Label lbSmsDateE;
	protected Label lbSmsStatus;
	protected Button btnSMSRetry;

	public DTxnDetailsUIDesign() {
		Design.read(this);
	}
}
