package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DTxnDetailsUIDesign extends VerticalLayout {
	protected VerticalLayout cMMRightContent;
	protected HorizontalLayout detailsHead;
	protected Panel detailsPanel;
	protected HorizontalLayout cBDHead21;
	protected VerticalLayout cBookingDetails2;
	protected HorizontalLayout cBDHead3;
	protected Label lbUN2;
	protected Label lbPass2;
	protected VerticalLayout cBookingDetails11;
	protected HorizontalLayout cBDHead11;
	protected Label lbUN11;
	protected Label lbPass11;
	protected VerticalLayout cBookingDetails21;
	protected HorizontalLayout cBDHead31;
	protected Label lbUN21;
	protected Label lbUN211;
	protected Label lbPass21;
	protected VerticalLayout cBookingDetails111;
	protected HorizontalLayout cBDHead111;
	protected Label lbUN111;
	protected Label lbPass111;
	protected Label lbPass1111;
	protected HorizontalLayout cBDHead2;
	protected VerticalLayout cBookingDetails;
	protected HorizontalLayout cBDHead;
	protected Label lbUN;
	protected Label lbPass;
	protected Label lbPass3;
	protected VerticalLayout cBookingDetails1;
	protected HorizontalLayout cBDHead1;
	protected Label lbUN1;
	protected Label lbPass1;
	protected VerticalLayout cBookingDetails3;
	protected HorizontalLayout cBDHead4;
	protected Label lbUN1111;
	protected Label lbPass1112;
	protected Label lbPass11111;
	protected VerticalLayout cBookingDetails12;
	protected HorizontalLayout cBDHead12;
	protected Label lbUN11111;
	protected Label lbPass11121;
	protected Label lbPass111111;
	protected HorizontalLayout cBDHead22;
	protected VerticalLayout cBookingDetails4;
	protected HorizontalLayout cBDHead5;
	protected Label lbUN3;
	protected Label lbPass4;
	protected VerticalLayout cBookingDetails13;
	protected HorizontalLayout cBDHead13;
	protected Label lbUN12;
	protected Label lbUN121;
	protected Label lbPass12;
	protected VerticalLayout cBookingDetails31;
	protected HorizontalLayout cBDHead41;
	protected Label lbUN11112;
	protected Label lbPass11122;
	protected VerticalLayout cBookingDetails121;
	protected HorizontalLayout cBDHead121;
	protected Label lbUN111111;
	protected Label lbPass111211;
	protected Label lbPass1111111;

	public DTxnDetailsUIDesign() {
		Design.read(this);
	}
}
