package com.lonestarcell.mtn.design.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DUserDetailsUIDesign extends VerticalLayout {
	protected VerticalLayout cMMRightContent;
	protected HorizontalLayout detailsHead;
	protected Panel detailsPanel;
	protected HorizontalLayout cBDHead21;
	protected VerticalLayout cBookingDetails2;
	protected HorizontalLayout cBDHead3;
	protected Label lbUserProfile;
	protected Label lbUsername;
	protected Label lbUserStatus;
	protected Button btnUserChangeCreds;
	protected Button btnUserChangeProfile;
	protected Button btnUserExpireSession;
	protected Button btnUserBlock;
	protected Button btnUserActivate;
	protected Button btnUserSetCreds;
	protected Button btnUserExpirePassword;
	protected VerticalLayout cBookingDetails11;
	protected HorizontalLayout cBDHead11;
	protected Label lbFirstName;
	protected Label lbSurname;
	protected Label lbLastName;
	protected Label lbEmail;
	protected Button btnUserEditPersonalInfo;
	protected VerticalLayout cBookingDetails21;
	protected HorizontalLayout cBDHead31;
	protected Label lbOrg;
	protected Label lbOrgDomain;
	protected Label lbOrgStatus;
	protected VerticalLayout cBookingDetails111;
	protected HorizontalLayout cBDHead111;
	protected Label lbCreateDate;
	protected Label lbLoginDate;
	protected Button btnUserRefresh;

	public DUserDetailsUIDesign() {
		Design.read(this);
	}
}
