package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BackupPanelUIDesign extends VerticalLayout {
	protected HorizontalLayout headerMain;
	protected VerticalLayout platformIdentity;
	protected VerticalLayout userIdentity;
	protected HorizontalLayout usernameMore;
	protected Label username;
	protected Button userOps;
	protected VerticalLayout moreDropDown;
	protected VerticalLayout midContent;
	protected Panel leftBar;
	protected VerticalLayout rightContent;
	protected Panel content;
	protected VerticalLayout allTodayFlights;
	protected VerticalLayout headBookedScheduledFlights5;
	protected VerticalLayout cDetailsScheduledFlights5;
	protected VerticalLayout bookedScheduledFlights;
	protected VerticalLayout headBookedScheduledFlights;
	protected VerticalLayout cDetailsScheduledFlights;
	protected VerticalLayout bookedChartedFlights;
	protected VerticalLayout headBookedScheduledFlights2;
	protected VerticalLayout cDetailsScheduledFlights2;
	protected VerticalLayout rescheduledFlights;
	protected VerticalLayout headBookedScheduledFlights3;
	protected VerticalLayout cDetailsScheduledFlights3;
	protected VerticalLayout cancelledFlights;
	protected VerticalLayout headBookedScheduledFlights4;
	protected VerticalLayout cDetailsScheduledFlights4;
	protected HorizontalLayout footerMain;
	protected Label footerYearSeparator;
	protected Label footerCurretYr;
	protected Label footerPlatformBoss;

	public BackupPanelUIDesign() {
		Design.read(this);
	}
}
