package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BackupDGeneralUIDesign extends VerticalLayout {
	protected VerticalLayout cHeader;
	protected VerticalLayout logoArea;
	protected Panel cMidContent;
	protected VerticalLayout cPay;
	protected VerticalLayout cMessage;
	protected HorizontalLayout cPayOptHeader;
	protected VerticalLayout cPayWelcomeMsg;
	protected VerticalLayout cPayHelp;
	protected VerticalLayout cAds;
	protected VerticalLayout cMobileAd;
	protected HorizontalLayout cMM2;
	protected VerticalLayout cMMSlogan2;
	protected VerticalLayout cCardAd;
	protected HorizontalLayout cMM3;
	protected VerticalLayout cMMSlogan3;
	protected VerticalLayout cSecurityAdd;
	protected HorizontalLayout cMM4;
	protected VerticalLayout cMMSlogan4;
	protected VerticalLayout cFooter;
	protected HorizontalLayout cFooterInner;
	protected HorizontalLayout cFooterRight;

	public BackupDGeneralUIDesign() {
		Design.read(this);
	}
}
