package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DDetailsUIDesign extends VerticalLayout {
	protected HorizontalLayout cPayStepsHead;
	protected HorizontalLayout cPayStepIndicator;
	protected HorizontalLayout cSteps;
	protected HorizontalLayout cStepOne;
	protected HorizontalLayout cStepOne2;
	protected HorizontalLayout cStepOne3;
	protected HorizontalLayout cStepOne4;
	protected HorizontalLayout cPayStepsBody;
	protected VerticalLayout cMMLeftContent;
	protected VerticalLayout cMMOp;
	protected HorizontalLayout cMM;
	protected VerticalLayout cMMSlogan;
	protected VerticalLayout cMMRightContent;
	protected HorizontalLayout mmPanelHead2;
	protected Panel mmPanel2;
	protected VerticalLayout cBookingDetails;
	protected HorizontalLayout cBDHead;
	protected HorizontalLayout cBDBody;
	protected Label lbName;
	protected Label lbBookingRef;
	protected Label lbCostUSD;
	protected Label lbRate;
	protected Label lbCostUGX;
	protected VerticalLayout cMobileNumber;
	protected Label lbErrorMsg;
	protected Label lbNormalMsg;
	protected TextField fMSISDN;
	protected TextField fMSISDNX;
	protected HorizontalLayout cControls;
	protected Button btnCancel;
	protected Button btnBack;
	protected Button btnNext;

	public DDetailsUIDesign() {
		Design.read(this);
	}
}
