package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DLoginUIDesign extends VerticalLayout {
	protected VerticalLayout cHeader;
	protected VerticalLayout logoArea;
	protected Panel cMidContent;
	protected VerticalLayout cMobileAd;
	protected VerticalLayout cForm;
	protected VerticalLayout cBookingDetails3;
	protected Label lbFormState;
	protected Label lbFormStateDesc;
	protected Label lbTimer;
	protected Label lbErrorMsg;
	protected Label lbNormalMsg;
	protected TextField fUsername;
	protected PasswordField fPassword;
	protected PasswordField fConfirmPassword;
	protected HorizontalLayout cControls;
	protected Button btnLogin;
	protected Button btnReset;
	protected VerticalLayout cFooter;
	protected HorizontalLayout cFooterInner;
	protected HorizontalLayout cOwnership;
	protected Label lbCRYearStart;
	protected Label lbYearSeparator;
	protected Label lbCRYearCurrent;
	protected Label lbClient;
	protected HorizontalLayout cFooterRight;

	public DLoginUIDesign() {
		Design.read(this);
	}
}
