package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DMMUIDesign extends VerticalLayout {
	protected VerticalLayout cHeader;
	protected VerticalLayout logoArea;
	protected Panel cMidContent;
	protected VerticalLayout cPay;
	protected HorizontalLayout cPayStepsHead;
	protected HorizontalLayout cPayStepIndicator;
	protected HorizontalLayout cSteps;
	protected HorizontalLayout cStepOne;
	protected HorizontalLayout cStepOne2;
	protected HorizontalLayout cStepOne3;
	protected HorizontalLayout cStepOne4;
	protected HorizontalLayout cPayStepsBody;
	protected VerticalLayout cMMLeftContent;
	protected VerticalLayout cMMOp;
	protected HorizontalLayout cMM;
	protected VerticalLayout cMMSlogan;
	protected VerticalLayout cMMRightContent;
	protected HorizontalLayout mmPanelHead2;
	protected Panel mmPanel2;
	protected VerticalLayout cForm;
	protected HorizontalLayout cControls;
	protected VerticalLayout cForm2;
	protected HorizontalLayout cControls2;
	protected HorizontalLayout cAds;
	protected VerticalLayout cFooter;
	protected HorizontalLayout cFooterInner;
	protected HorizontalLayout cFooterRight;

	public DMMUIDesign() {
		Design.read(this);
	}
}
