package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DPaymentStateUIDesign extends VerticalLayout {
	protected VerticalLayout cMMRightContent;
	protected HorizontalLayout mmPanelHead2;
	protected Label lbPopupDescription;
	protected Panel mmPanel2;
	protected VerticalLayout cBookingDetails;
	protected Button btnSuccess;
	protected Button btnFailed;
	protected Label lbSpinner;
	protected Label lbState;
	protected Label lbDescription;
	protected Label lbDescription2;
	protected Button btnPhoneIcon;
	protected Label lbMSISDN;
	protected VerticalLayout cApprovalSteps;
	protected Label lbRefreshWarning2;
	protected Label lbRefreshWarning3;
	protected Label lbRefreshWarning4;
	protected Label lbRefreshWarning5;
	protected Label lbRefreshWarning;
	protected Button btnClose;

	public DPaymentStateUIDesign() {
		Design.read(this);
	}
}
