package com.lonestarcell.mtn.design.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DPaymentUIDesign extends VerticalLayout {
	protected HorizontalLayout cPayOptHeader;
	protected VerticalLayout cPayWelcomeMsg;
	protected VerticalLayout cPayHelp;
	protected HorizontalLayout cPayOpt;
	protected VerticalLayout cMobileMoney;
	protected HorizontalLayout mmPanelHead;
	protected Panel mmPanel;
	protected VerticalLayout cMMList;
	protected HorizontalLayout listItemMTN;
	protected HorizontalLayout btnTrial;
	protected VerticalLayout cCard;
	protected HorizontalLayout mmPanelHead2;
	protected Panel mmPanel2;
	protected VerticalLayout cMMList2;

	public DPaymentUIDesign() {
		Design.read(this);
	}
}
